### ISSUE TITLE
Incompatible with my mod, because you overwrite the entire method renderFirstPersonItem.

### ISSUE THREAD

**Issue by eleqz** [spiderfrog3000/OldCombatMod#1]
Instead of using @Overwrite for method renderFirstPersonItem, you should @Inject into the method. As right now, any mod that uses the same method as you in that mixin is incompatible with your mod. 

Cool mod idea though, but could be refined a lot more.

My mod
https://modrinth.com/mod/cpvp

> `Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [smallpop.mixins.json:HeldItemRenderMixin from mod smallpop] from phase [DEFAULT] in config [smallpop.mixins.json] FAILED during APPLY`

> `Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_759::renderFirstPersonItem with priority 1000 cannot inject into net/minecraft/class_759::method_3228(Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;I)V merged by com.spiderfrog.oldcombatmod.mixin.render.MixinHeldItemRenderer with priority 1000 [PREINJECT Applicator Phase -> smallpop.mixins.json:HeldItemRenderMixin from mod smallpop -> Prepare Injections ->  -> handler$bgj000$smallpop$renderFirstPersonItem(Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]`

**Comment by spiderfrog3000** [comment]
thanks for the report.
fixed now.
