### ISSUE TITLE
Create map crash

### ISSUE THREAD

**Issue by zc1108aaa** [spiderfrog3000/OldCombatMod#3]
[latest.log](https://github.com/spiderfrog3000/OldCombatMod/files/15258571/latest.log)
111
[crash-2024-05-09_14.45.04-server.txt](https://github.com/spiderfrog3000/OldCombatMod/files/15258573/crash-2024-05-09_14.45.04-server.txt)

**Comment by spiderfrog3000** [comment]
Hello,

thats not a crashlog of my mod.
