### ISSUE TITLE
weird floor swinging

### ISSUE THREAD

**Issue by Ilovechickennuggets1** [spiderfrog3000/OldCombatMod#4]
everytime i swing at the floor, everyone on my client will also start swinging, pretty odd

**Comment by spiderfrog3000** [comment]
well, it should not work like that xD Which Minecraft version do u play on?

**Comment by Ilovechickennuggets1** [comment]
i play on 1.20.4

**Comment by Ilovechickennuggets1** [comment]
https://github.com/spiderfrog3000/OldCombatMod/assets/99118485/7459dece-ebe4-4eef-a5c5-3077db4a8865

this is what i mean, i tested it in like three servers

**Comment by spiderfrog3000** [comment]
Fixed with Version 0.1.3, thanks for the report

**Comment by Ilovechickennuggets1** [comment]
np
